format = "$all$directory$character"

[time]
disabled = false

[kubernetes]
disabled = false
format = 'on [â›µ $context \($namespace\)](dimmed green) '

[aws]
format = 'on [$symbol($profile )(\($region\) )]($style)'
style = "bold blue"
symbol = "ğŸ…° "

[docker_context]
format = "via [ğŸ‹ $context](blue bold)"
only_with_files = false
